// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
  islandState: () => __TAURI_INVOKE<IslandState_Serialize>("island_state"),
  islandOpen: () => __TAURI_INVOKE<IslandState_Serialize>("island_open"),
  islandCollapse: () =>
    __TAURI_INVOKE<IslandState_Serialize>("island_collapse"),
  activityAction: (
    pluginId: string,
    actionId: string,
    payload: string | null,
  ) =>
    typedError<null, string>(
      __TAURI_INVOKE("activity_action", { pluginId, actionId, payload }),
    ),
  getSettings: () => __TAURI_INVOKE<AppSettings>("get_settings"),
  setSettings: (settings: AppSettings) =>
    typedError<AppSettings, string>(
      __TAURI_INVOKE("set_settings", { settings }),
    ),
  setLayout: (layout: HomeLayout) =>
    typedError<HomeLayout, string>(__TAURI_INVOKE("set_layout", { layout })),
  listPlugins: () => __TAURI_INVOKE<PluginRecord[]>("list_plugins"),
  enablePlugin: (id: string) =>
    typedError<PluginRecord, string>(__TAURI_INVOKE("enable_plugin", { id })),
  disablePlugin: (id: string) =>
    typedError<PluginRecord, string>(__TAURI_INVOKE("disable_plugin", { id })),
  reloadPlugin: (id: string) =>
    typedError<PluginRecord, string>(__TAURI_INVOKE("reload_plugin", { id })),
  uninstallPlugin: (id: string) =>
    typedError<null, string>(__TAURI_INVOKE("uninstall_plugin", { id })),
  dismissActivity: (activityId: string) =>
    __TAURI_INVOKE<IslandState_Serialize>("dismiss_activity", { activityId }),
  listThemes: () => __TAURI_INVOKE<ThemeDocument[]>("list_themes"),
  currentTheme: () => __TAURI_INVOKE<ThemeDocument>("current_theme"),
  applyTheme: (id: string) =>
    typedError<ThemeDocument, string>(__TAURI_INVOKE("apply_theme", { id })),
  mediaArtwork: (sessionId: string) =>
    __TAURI_INVOKE<string | null>("media_artwork", { sessionId }),
  listMonitors: () =>
    typedError<MonitorInfo[], string>(__TAURI_INVOKE("list_monitors")),
  checkUpdates: () => __TAURI_INVOKE<UpdateStatus>("check_updates"),
  setIslandPresence: (
    mode: string,
    width: number | null,
    height: number | null,
  ) =>
    typedError<null, string>(
      __TAURI_INVOKE("set_island_presence", { mode, width, height }),
    ),
};

/* Types */
/**
 *  The generic lifecycle an Activity represents. Plugins describe what kind of
 *  information they carry through this semantic metadata; the engine never
 *  matches on plugin ids.
 */
export type ActivityLifecycle =
  /**  A short-lived one-shot event (volume change, device connect). */
  | "momentary"
  /**
   *  Persistent state that stays relevant until dismissed (now playing,
   *  idle clock).
   */
  | "ongoing"
  /**  An operation that advances over time (transfer, install). */
  | "progress"
  /**  A deadline / countdown whose urgency rises as it approaches. */
  | "countdown"
  /**  A result that finished (timer completed, screenshot saved). */
  | "completion"
  /**  Something that needs attention now (alarm, alert). */
  | "alert";

/**
 *  The semantic descriptor of one Activity. Activities *exist* here regardless
 *  of whether they are currently drawn; presentation is decided downstream by
 *  the composition engine.
 */
export type ActivitySnapshot =
  | ActivitySnapshot_Serialize
  | ActivitySnapshot_Deserialize;

/**
 *  The semantic descriptor of one Activity. Activities *exist* here regardless
 *  of whether they are currently drawn; presentation is decided downstream by
 *  the composition engine.
 */
export type ActivitySnapshot_Deserialize = {
  /**  Stable identity across updates. */
  activityId: string;
  /**  Source plugin. */
  pluginId: string;
  /**  Optional stable identity per logical instance. */
  instanceId?: string | null;
  /**  Group / coalescing identity: updates in the same group replace one slot. */
  group?: string | null;
  lifecycle?: ActivityLifecycle;
  attention?: Attention_Deserialize;
  /**
   *  Absolute wall-clock deadline (ms since epoch). Lets the engine derive
   *  dynamic urgency for countdowns generically.
   */
  deadlineMs?: number | null;
  /**
   *  Transient window: how long a transient presentation stays relevant after
   *  its last update. `None` means the Activity is resident and persists.
   */
  lifetimeMs?: number | null;
  /**  The compact presentation variants the engine may choose from. */
  variants?: PresentationVariant_Deserialize[];
  /**  The expanded face shown when the island is opened. */
  expanded?: UiNode_Deserialize | null;
  /**  Small widget preview for the home customization surface. */
  preview?: UiNode_Deserialize | null;
  timestampMs?: number | null;
};

/**
 *  The semantic descriptor of one Activity. Activities *exist* here regardless
 *  of whether they are currently drawn; presentation is decided downstream by
 *  the composition engine.
 */
export type ActivitySnapshot_Serialize = {
  /**  Stable identity across updates. */
  activityId: string;
  /**  Source plugin. */
  pluginId: string;
  /**  Optional stable identity per logical instance. */
  instanceId?: string | null;
  /**  Group / coalescing identity: updates in the same group replace one slot. */
  group?: string | null;
  lifecycle: ActivityLifecycle;
  attention: Attention_Serialize;
  /**
   *  Absolute wall-clock deadline (ms since epoch). Lets the engine derive
   *  dynamic urgency for countdowns generically.
   */
  deadlineMs?: number | null;
  /**
   *  Transient window: how long a transient presentation stays relevant after
   *  its last update. `None` means the Activity is resident and persists.
   */
  lifetimeMs?: number | null;
  /**  The compact presentation variants the engine may choose from. */
  variants: PresentationVariant_Serialize[];
  /**  The expanded face shown when the island is opened. */
  expanded?: UiNode_Serialize | null;
  /**  Small widget preview for the home customization surface. */
  preview?: UiNode_Serialize | null;
  timestampMs: number | null;
};

export type Align = "center" | "start" | "end" | "stretch";

export type AppSettings = {
  islandEnabled: boolean;
  autostart: boolean;
  monitor: MonitorPreference;
  hideOnFullscreen: boolean;
  themeId: string;
  hoverOpenMs: number;
  hoverCloseMs: number;
  reducedMotion: boolean | null;
  enabledPlugins: { [key in string]: boolean };
  layout: HomeLayout;
  pluginSettings: { [key in string]: { [key in string]: JsonValue } };
  idleProvider?: IdleProvider;
  composition?: CompositionPreference;
  clock?: ClockSettings;
};

/**
 *  Generic attention characteristics. These are distinct semantic dimensions,
 *  not one priority integer: a volume bump is high-urgency / low-persistence,
 *  a timer is moderate-urgency / high-persistence, now playing is
 *  low-urgency / high-context.
 */
export type Attention = Attention_Serialize | Attention_Deserialize;

/**
 *  Generic attention characteristics. These are distinct semantic dimensions,
 *  not one priority integer: a volume bump is high-urgency / low-persistence,
 *  a timer is moderate-urgency / high-persistence, now playing is
 *  low-urgency / high-context.
 */
export type Attention_Deserialize = {
  /**  Base importance 0..1. */
  importance?: number | null;
  /**  Base urgency 0..1 at publish time. */
  urgency?: number | null;
  /**
   *  How long (ms) the Activity stays relevant after its last update.
   *  `None` means it is resident and never freshness-expires on its own.
   */
  freshnessMs?: number | null;
  /**
   *  Window (ms) before `deadline_ms` during which urgency ramps from
   *  `urgency` toward 1.0. Generic: only meaningful when a deadline exists.
   *  The plugin expresses its own semantic progression; the engine derives
   *  the curve from these generic fields.
   */
  urgencyWindowMs?: number | null;
  /**  Long-term value 0..1 — how worth keeping resident this information is. */
  persistence?: number | null;
  /**  Whether the Activity can be removed from the composition cheaply. */
  interruptible?: boolean;
  /**
   *  Whether the Activity is suitable to take over the whole island
   *  temporarily (transients like volume, timer completion).
   */
  takeoverSuitable?: boolean;
};

/**
 *  Generic attention characteristics. These are distinct semantic dimensions,
 *  not one priority integer: a volume bump is high-urgency / low-persistence,
 *  a timer is moderate-urgency / high-persistence, now playing is
 *  low-urgency / high-context.
 */
export type Attention_Serialize = {
  /**  Base importance 0..1. */
  importance: number | null;
  /**  Base urgency 0..1 at publish time. */
  urgency: number | null;
  /**
   *  How long (ms) the Activity stays relevant after its last update.
   *  `None` means it is resident and never freshness-expires on its own.
   */
  freshnessMs?: number | null;
  /**
   *  Window (ms) before `deadline_ms` during which urgency ramps from
   *  `urgency` toward 1.0. Generic: only meaningful when a deadline exists.
   *  The plugin expresses its own semantic progression; the engine derives
   *  the curve from these generic fields.
   */
  urgencyWindowMs?: number | null;
  /**  Long-term value 0..1 — how worth keeping resident this information is. */
  persistence: number | null;
  /**  Whether the Activity can be removed from the composition cheaply. */
  interruptible: boolean;
  /**
   *  Whether the Activity is suitable to take over the whole island
   *  temporarily (transients like volume, timer completion).
   */
  takeoverSuitable: boolean;
};

export type ClockMotion = "tick" | "smooth";

export type ClockSettings = {
  showSeconds?: boolean;
  motion?: ClockMotion;
};

export type CompositionPreference =
  /**  The engine decides how much information to show automatically. */
  | "auto"
  /**  Prefer less information: strong width pressure, few segments. */
  | "minimal"
  /**  Prefer more information: relaxed width pressure, richer variants. */
  | "rich";

/**
 *  Semantic presentation density. Names are not pixel widths; they are
 *  information-density levels the engine trades off against space.
 */
export type Density =
  /**  A single indicator (icon, dot). */
  | "micro"
  /**  One compact datum (a short number or name). */
  | "small"
  /**  A small composed unit (icon + datum). */
  | "compact"
  /**  A richer unit (icon + label + secondary detail). */
  | "richCompact"
  /**  The expanded face. */
  | "expanded";

export type HomeLayout = {
  items: string[];
};

export type IdleProvider =
  | { kind: "clock" }
  | { kind: "none" }
  | { kind: "media" }
  | { kind: "plugin"; id: string };

export type IslandState = IslandState_Serialize | IslandState_Deserialize;

export type IslandState_Deserialize = {
  presence: Presence;
  sticky: boolean;
  activities: ActivitySnapshot_Deserialize[];
};

export type IslandState_Serialize = {
  presence: Presence;
  sticky: boolean;
  activities: ActivitySnapshot_Serialize[];
};

/**
 *  An arbitrary JSON value with a TS-safe number representation (f64). Used for
 *  plugin settings so the typed bridge exports `Record<string, JsonValue>`
 *  instead of BigInt-incompatible `serde_json::Value`.
 */
export type JsonValue =
  | "Null"
  | boolean
  | number
  | null
  | string
  | JsonValue[]
  | { [key in string]: JsonValue };

export type MonitorInfo = {
  id: string;
  name: string;
  primary: boolean;
};

export type MonitorPreference =
  | { mode: "primary" }
  | { mode: "selected"; id: string };

export type MotionTokens = {
  peek: Spring;
  expand: Spring;
  collapse: Spring;
  contentEnterMs: number;
  contentExitMs: number;
  page: Spring;
  drag: Spring;
  activitySwitch: Spring;
};

export type Permissions = {
  network?: string[];
  storage?: boolean;
  media?: boolean;
  audio?: boolean;
  devices?: boolean;
};

export type PluginLifecycle =
  | "discovered"
  | "validated"
  | "installed"
  | "enabled"
  | "running"
  | "disabled"
  | "failed";

export type PluginManifest = {
  id: string;
  name: string;
  version: string;
  api_version?: string;
  author?: string | null;
  description?: string | null;
  homepage?: string | null;
  repository?: string | null;
  icon?: string | null;
  minimum_engine_version?: string | null;
  entry?: string | null;
  enabled_by_default?: boolean;
  provides: Provides;
  permissions?: Permissions;
  settings_schema?: SettingField[];
};

export type PluginRecord = {
  id: string;
  manifest: PluginManifest;
  root: string;
  componentPath: string | null;
  themePath: string | null;
  enabled: boolean;
  error: string | null;
  iconUrl: string | null;
  state: PluginLifecycle;
};

export type Presence = "resting" | "peek" | "presentation" | "expanded";

/**
 *  One presentation variant of an Activity: a declarative UI node plus the
 *  metadata the composition engine needs to reason about its cost and value.
 */
export type PresentationVariant =
  | PresentationVariant_Serialize
  | PresentationVariant_Deserialize;

/**
 *  One presentation variant of an Activity: a declarative UI node plus the
 *  metadata the composition engine needs to reason about its cost and value.
 */
export type PresentationVariant_Deserialize = {
  density: Density;
  node?: UiNode_Deserialize | null;
  minWidth?: number;
  preferredWidth: number;
  maxWidth?: number | null;
  /**  Information utility 0..1 for this density. */
  utility?: number | null;
  /**  How long this variant must stay readable before it may swap. */
  minReadableMs?: number | null;
  /**
   *  Whether this variant may sit next to other segments. `false` means it
   *  must be the only thing on the face.
   */
  coexist?: boolean;
  /**  Optional human label for diagnostics only. */
  label?: string | null;
};

/**
 *  One presentation variant of an Activity: a declarative UI node plus the
 *  metadata the composition engine needs to reason about its cost and value.
 */
export type PresentationVariant_Serialize = {
  density: Density;
  node: UiNode_Serialize | null;
  minWidth: number;
  preferredWidth: number;
  maxWidth?: number | null;
  /**  Information utility 0..1 for this density. */
  utility: number | null;
  /**  How long this variant must stay readable before it may swap. */
  minReadableMs?: number | null;
  /**
   *  Whether this variant may sit next to other segments. `false` means it
   *  must be the only thing on the face.
   */
  coexist: boolean;
  /**  Optional human label for diagnostics only. */
  label?: string | null;
};

export type Provides = {
  activity?: boolean;
  theme?: boolean;
  app?: boolean;
  /**
   *  Activity plugins can be "utilities": they only present transiently and
   *  never occupy a home widget slot.
   */
  widget?: boolean;
};

export type SelectOption = {
  value: string;
  label: string;
};

export type SettingField =
  | {
      type: "boolean";
      key: string;
      label: string;
      description?: string | null;
      default?: boolean;
    }
  | {
      type: "string";
      key: string;
      label: string;
      description?: string | null;
      default?: string | null;
      secret?: boolean;
    }
  | {
      type: "number";
      key: string;
      label: string;
      description?: string | null;
      default?: number | null;
      min?: number | null;
      max?: number | null;
    }
  | {
      type: "select";
      key: string;
      label: string;
      options: SelectOption[];
      default?: string | null;
    }
  | {
      type: "slider";
      key: string;
      label: string;
      min: number | null;
      max: number | null;
      step?: number | null;
      default?: number | null;
    }
  | { type: "action"; key: string; label: string; description?: string | null }
  | { type: "secret"; key: string; label: string; description?: string | null };

export type Spring = {
  stiffness: number | null;
  damping: number | null;
  mass: number | null;
};

export type TextVariant = "body" | "title" | "kicker" | "numeric";

export type ThemeDocument = {
  id: string;
  name: string;
  description?: string | null;
  tokens: ThemeTokens;
  motion?: MotionTokens;
};

export type ThemeTokens = {
  shell: string;
  foreground: string;
  muted: string;
  accent: string;
  surface: string;
  opacity?: number | null;
  blur?: number | null;
  border?: string;
  shadow?: string;
  radius?: number | null;
};

export type UiNode = UiNode_Serialize | UiNode_Deserialize;

export type UiNode_Deserialize =
  | ({ kind: "text"; text: string; variant?: TextVariant } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
    })
  | ({ kind: "secondaryText"; text: string } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "icon"; name: string } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "image"; src: string; alt?: string } & {
      action?: never;
      active?: never;
      align?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "artwork"; src: string; alt?: string } & {
      action?: never;
      active?: never;
      align?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "button"; id: string; label?: string; icon?: string | null } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({
      kind: "iconButton";
      id: string;
      icon: string;
      label?: string;
      size?: string | null;
    } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "progress"; value: number | null; max?: number | null } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({
      kind: "countdown";
      /**
       *  Absolute wall-clock deadline (ms since epoch). The frontend
       *  interpolates locally between authoritative sync points.
       */
      deadlineMs: number | null;
      /**  Whether the countdown is actively running. */
      running?: boolean;
      /**  Remaining time when paused (ms). */
      pausedRemainingMs?: number | null;
      /**  Total duration for progress context (ms). */
      totalMs?: number | null;
    } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      positionMs?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({
      kind: "ruler";
      /**  Currently selected value (ms). */
      valueMs: number | null;
      minMs: number | null;
      maxMs: number | null;
      /**  Snap increment (ms). The frontend chooses adaptive tick density. */
      snapMs?: number | null;
      /**  Action id emitted when the value is committed. */
      action: string;
    } & {
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      variant?: never;
    })
  | ({
      kind: "seekBar";
      positionMs: number | null;
      durationMs: number | null;
      action: string;
    } & {
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "toggle"; id: string; on: boolean; label?: string } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "badge"; text: string } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "separator" } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "spacer"; size?: number; grow?: boolean } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "waveform"; active?: boolean } & {
      action?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({
      kind: "row";
      children?: UiNode_Deserialize[];
      gap?: number;
      align?: Align;
    } & {
      action?: never;
      active?: never;
      alt?: never;
      deadlineMs?: never;
      durationMs?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "column"; children?: UiNode_Deserialize[]; gap?: number } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      deadlineMs?: never;
      durationMs?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "stack"; children?: UiNode_Deserialize[] } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    });

export type UiNode_Serialize =
  | ({ kind: "text"; text: string; variant: TextVariant } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
    })
  | ({ kind: "secondaryText"; text: string } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "icon"; name: string } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "image"; src: string; alt: string } & {
      action?: never;
      active?: never;
      align?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "artwork"; src: string; alt: string } & {
      action?: never;
      active?: never;
      align?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "button"; id: string; label: string; icon: string | null } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({
      kind: "iconButton";
      id: string;
      icon: string;
      label: string;
      size: string | null;
    } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "progress"; value: number | null; max: number | null } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({
      kind: "countdown";
      /**
       *  Absolute wall-clock deadline (ms since epoch). The frontend
       *  interpolates locally between authoritative sync points.
       */
      deadlineMs: number | null;
      /**  Whether the countdown is actively running. */
      running: boolean;
      /**  Remaining time when paused (ms). */
      pausedRemainingMs?: number | null;
      /**  Total duration for progress context (ms). */
      totalMs?: number | null;
    } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      positionMs?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({
      kind: "ruler";
      /**  Currently selected value (ms). */
      valueMs: number | null;
      minMs: number | null;
      maxMs: number | null;
      /**  Snap increment (ms). The frontend chooses adaptive tick density. */
      snapMs?: number | null;
      /**  Action id emitted when the value is committed. */
      action: string;
    } & {
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      variant?: never;
    })
  | ({
      kind: "seekBar";
      positionMs: number | null;
      durationMs: number | null;
      action: string;
    } & {
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "toggle"; id: string; on: boolean; label: string } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "badge"; text: string } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "separator" } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "spacer"; size: number; grow: boolean } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "waveform"; active: boolean } & {
      action?: never;
      align?: never;
      alt?: never;
      children?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({
      kind: "row";
      children: UiNode_Serialize[];
      gap: number;
      align: Align;
    } & {
      action?: never;
      active?: never;
      alt?: never;
      deadlineMs?: never;
      durationMs?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "column"; children: UiNode_Serialize[]; gap: number } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      deadlineMs?: never;
      durationMs?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    })
  | ({ kind: "stack"; children: UiNode_Serialize[] } & {
      action?: never;
      active?: never;
      align?: never;
      alt?: never;
      deadlineMs?: never;
      durationMs?: never;
      gap?: never;
      grow?: never;
      icon?: never;
      id?: never;
      label?: never;
      max?: never;
      maxMs?: never;
      minMs?: never;
      name?: never;
      on?: never;
      pausedRemainingMs?: never;
      positionMs?: never;
      running?: never;
      size?: never;
      snapMs?: never;
      src?: never;
      text?: never;
      totalMs?: never;
      value?: never;
      valueMs?: never;
      variant?: never;
    });

export type UpdateStatus = {
  available: boolean;
  version: string | null;
  message: string;
};

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>,
): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
  try {
    return { status: "ok", data: await result };
  } catch (e) {
    if (e instanceof Error) throw e;
    return { status: "error", error: e as any };
  }
}
