// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
  islandState: () => __TAURI_INVOKE<IslandState_Serialize>("island_state"),
  islandOpen: () => __TAURI_INVOKE<IslandState_Serialize>("island_open"),
  islandCollapse: () =>
    __TAURI_INVOKE<IslandState_Serialize>("island_collapse"),
  activityAction: (
    pluginId: string,
    actionId: string,
    payload: string | null,
  ) =>
    typedError<null, string>(
      __TAURI_INVOKE("activity_action", { pluginId, actionId, payload }),
    ),
  getSettings: () => __TAURI_INVOKE<AppSettings>("get_settings"),
  setSettings: (settings: AppSettings) =>
    typedError<AppSettings, string>(
      __TAURI_INVOKE("set_settings", { settings }),
    ),
  setLayout: (layout: HomeLayout) =>
    typedError<HomeLayout, string>(__TAURI_INVOKE("set_layout", { layout })),
  listPlugins: () => __TAURI_INVOKE<PluginRecord[]>("list_plugins"),
  enablePlugin: (id: string) =>
    typedError<PluginRecord, string>(__TAURI_INVOKE("enable_plugin", { id })),
  disablePlugin: (id: string) =>
    typedError<PluginRecord, string>(__TAURI_INVOKE("disable_plugin", { id })),
  reloadPlugin: (id: string) =>
    typedError<PluginRecord, string>(__TAURI_INVOKE("reload_plugin", { id })),
  uninstallPlugin: (id: string) =>
    typedError<null, string>(__TAURI_INVOKE("uninstall_plugin", { id })),
  dismissActivity: (activityId: string) =>
    __TAURI_INVOKE<IslandState_Serialize>("dismiss_activity", { activityId }),
  listThemes: () => __TAURI_INVOKE<ThemeDocument[]>("list_themes"),
  currentTheme: () => __TAURI_INVOKE<ThemeDocument>("current_theme"),
  applyTheme: (id: string) =>
    typedError<ThemeDocument, string>(__TAURI_INVOKE("apply_theme", { id })),
  mediaArtwork: (sessionId: string) =>
    __TAURI_INVOKE<string | null>("media_artwork", { sessionId }),
  listMonitors: () =>
    typedError<MonitorInfo[], string>(__TAURI_INVOKE("list_monitors")),
  checkUpdates: () => __TAURI_INVOKE<UpdateStatus>("check_updates"),
  setIslandPresence: (
    mode: string,
    width: number | null,
    height: number | null,
  ) =>
    typedError<null, string>(
      __TAURI_INVOKE("set_island_presence", { mode, width, height }),
    ),
};

/* Types */
export type ActivitySnapshot =
  | ActivitySnapshot_Serialize
  | ActivitySnapshot_Deserialize;

export type ActivitySnapshot_Deserialize = {
  activityId: string;
  pluginId: string;
  priority: number;
  mode: PresentationMode;
  lifetimeMs: number | null;
  interruptible: boolean;
  compact: UiNode | null;
  peek: UiNode | null;
  presentation: UiNode | null;
  expanded: UiNode | null;
  preview?: UiNode | null;
  timestampMs?: number | null;
  /**
   *  Updates sharing a coalescing key replace one presentation instead of
   *  being queued. Generic; a transient surface (for example a system volume
   *  or device change) keeps one live presentation across many updates.
   */
  coalescingKey?: string | null;
  /**  Preferred presentation width intent. Generic sizing hint. */
  preferredSize?: PreferredSize | null;
};

export type ActivitySnapshot_Serialize = {
  activityId: string;
  pluginId: string;
  priority: number;
  mode: PresentationMode;
  lifetimeMs: number | null;
  interruptible: boolean;
  compact: UiNode | null;
  peek: UiNode | null;
  presentation: UiNode | null;
  expanded: UiNode | null;
  preview: UiNode | null;
  timestampMs: number | null;
  /**
   *  Updates sharing a coalescing key replace one presentation instead of
   *  being queued. Generic; a transient surface (for example a system volume
   *  or device change) keeps one live presentation across many updates.
   */
  coalescingKey?: string | null;
  /**  Preferred presentation width intent. Generic sizing hint. */
  preferredSize?: PreferredSize | null;
};

export type Align = "center" | "start" | "end" | "stretch";

export type AppSettings = {
  islandEnabled: boolean;
  autostart: boolean;
  monitor: MonitorPreference;
  hideOnFullscreen: boolean;
  themeId: string;
  hoverOpenMs: number;
  hoverCloseMs: number;
  reducedMotion: boolean | null;
  enabledPlugins: { [key in string]: boolean };
  layout: HomeLayout;
  pluginSettings: { [key in string]: { [key in string]: JsonValue } };
  idleProvider?: IdleProvider;
};

export type HomeLayout = {
  items: string[];
};

export type IdleProvider =
  | { kind: "clock" }
  | { kind: "none" }
  | { kind: "media" }
  | { kind: "plugin"; id: string };

export type IslandState = IslandState_Serialize | IslandState_Deserialize;

export type IslandState_Deserialize = {
  presence: Presence;
  sticky: boolean;
  activity: ActivitySnapshot_Deserialize | null;
  activities: ActivitySnapshot_Deserialize[];
};

export type IslandState_Serialize = {
  presence: Presence;
  sticky: boolean;
  activity: ActivitySnapshot_Serialize | null;
  activities: ActivitySnapshot_Serialize[];
};

/**
 *  An arbitrary JSON value with a TS-safe number representation (f64). Used for
 *  plugin settings so the typed bridge exports `Record<string, JsonValue>`
 *  instead of BigInt-incompatible `serde_json::Value`.
 */
export type JsonValue =
  | "Null"
  | boolean
  | number
  | null
  | string
  | JsonValue[]
  | { [key in string]: JsonValue };

export type MonitorInfo = {
  id: string;
  name: string;
  primary: boolean;
};

export type MonitorPreference =
  | { mode: "primary" }
  | { mode: "selected"; id: string };

export type MotionTokens = {
  peek: Spring;
  expand: Spring;
  collapse: Spring;
  contentEnterMs: number;
  contentExitMs: number;
  page: Spring;
  drag: Spring;
  activitySwitch: Spring;
};

export type Permissions = {
  network?: string[];
  storage?: boolean;
  media?: boolean;
  audio?: boolean;
  devices?: boolean;
};

export type PluginLifecycle =
  | "discovered"
  | "validated"
  | "installed"
  | "enabled"
  | "running"
  | "disabled"
  | "failed";

export type PluginManifest = {
  id: string;
  name: string;
  version: string;
  api_version?: string;
  author?: string | null;
  description?: string | null;
  homepage?: string | null;
  repository?: string | null;
  icon?: string | null;
  minimum_engine_version?: string | null;
  entry?: string | null;
  enabled_by_default?: boolean;
  provides: Provides;
  permissions?: Permissions;
  settings_schema?: SettingField[];
};

export type PluginRecord = {
  id: string;
  manifest: PluginManifest;
  root: string;
  componentPath: string | null;
  themePath: string | null;
  enabled: boolean;
  error: string | null;
  iconUrl: string | null;
  state: PluginLifecycle;
};

/**
 *  How wide the island should prefer to be for this activity. The renderer
 *  stays authoritative over final geometry; plugins only describe intent.
 */
export type PreferredSize =
  /**  Content-driven within the standard face bounds. */
  | "auto"
  /**  Small, clock-like surfaces. */
  | "compact"
  /**  Medium-wide surfaces such as level meters. */
  | "medium"
  /**  Wide surfaces such as player chrome. */
  | "wide";

export type Presence = "resting" | "peek" | "presentation" | "expanded";

export type PresentationMode = "compact" | "peek" | "presentation" | "expanded";

export type Provides = {
  activity?: boolean;
  theme?: boolean;
  app?: boolean;
  /**
   *  Activity plugins can be "utilities": they only present transiently and
   *  never occupy a home widget slot.
   */
  widget?: boolean;
};

export type SelectOption = {
  value: string;
  label: string;
};

export type SettingField =
  | {
      type: "boolean";
      key: string;
      label: string;
      description?: string | null;
      default?: boolean;
    }
  | {
      type: "string";
      key: string;
      label: string;
      description?: string | null;
      default?: string | null;
      secret?: boolean;
    }
  | {
      type: "number";
      key: string;
      label: string;
      description?: string | null;
      default?: number | null;
      min?: number | null;
      max?: number | null;
    }
  | {
      type: "select";
      key: string;
      label: string;
      options: SelectOption[];
      default?: string | null;
    }
  | {
      type: "slider";
      key: string;
      label: string;
      min: number | null;
      max: number | null;
      step?: number | null;
      default?: number | null;
    }
  | { type: "action"; key: string; label: string; description?: string | null }
  | { type: "secret"; key: string; label: string; description?: string | null };

export type Spring = {
  stiffness: number | null;
  damping: number | null;
  mass: number | null;
};

export type TextVariant = "body" | "title" | "kicker" | "numeric";

export type ThemeDocument = {
  id: string;
  name: string;
  description?: string | null;
  tokens: ThemeTokens;
  motion?: MotionTokens;
};

export type ThemeTokens = {
  shell: string;
  foreground: string;
  muted: string;
  accent: string;
  surface: string;
  opacity?: number | null;
  blur?: number | null;
  border?: string;
  shadow?: string;
  radius?: number | null;
};

export type UiNode =
  | { kind: "text"; text: string; variant?: TextVariant }
  | { kind: "secondaryText"; text: string }
  | { kind: "icon"; name: string }
  | { kind: "image"; src: string; alt?: string }
  | { kind: "artwork"; src: string; alt?: string }
  | { kind: "button"; id: string; label?: string; icon?: string | null }
  | {
      kind: "iconButton";
      id: string;
      icon: string;
      label?: string;
      size?: string | null;
    }
  | { kind: "progress"; value: number | null; max?: number | null }
  | {
      kind: "seekBar";
      positionMs: number | null;
      durationMs: number | null;
      action: string;
    }
  | { kind: "toggle"; id: string; on: boolean; label?: string }
  | { kind: "badge"; text: string }
  | { kind: "separator" }
  | { kind: "spacer"; size?: number; grow?: boolean }
  | { kind: "waveform"; active?: boolean }
  | { kind: "row"; children?: UiNode[]; gap?: number; align?: Align }
  | { kind: "column"; children?: UiNode[]; gap?: number }
  | { kind: "stack"; children?: UiNode[] };

export type UpdateStatus = {
  available: boolean;
  version: string | null;
  message: string;
};

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>,
): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
  try {
    return { status: "ok", data: await result };
  } catch (e) {
    if (e instanceof Error) throw e;
    return { status: "error", error: e as any };
  }
}
